//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessModels.Resources.AppLang", typeof(AppLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa thư mục gốc.
        /// </summary>
        public static string Could_not_delete_root_folder {
            get {
                return ResourceManager.GetString("Could not delete root folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy siêu dữ liệu.
        /// </summary>
        public static string Could_not_found_metadata {
            get {
                return ResourceManager.GetString("Could not found metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài khoản.
        /// </summary>
        public static string Create_Account {
            get {
                return ResourceManager.GetString("Create Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo thất bại.
        /// </summary>
        public static string Create_failed {
            get {
                return ResourceManager.GetString("Create failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo thành công.
        /// </summary>
        public static string Create_successfully {
            get {
                return ResourceManager.GetString("Create successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chế độ tối.
        /// </summary>
        public static string Dark_mode {
            get {
                return ResourceManager.GetString("Dark mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string Delete_successfully {
            get {
                return ResourceManager.GetString("Delete successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không sử dụng mã thông báo này trên máy chủ cung cấp mã thông báo này.
        /// </summary>
        public static string Do_not_use_this_token_on_a_server_that_provides_this_token {
            get {
                return ResourceManager.GetString("Do not use this token on a server that provides this token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mật khẩu.
        /// </summary>
        public static string Enter_password {
            get {
                return ResourceManager.GetString("Enter password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tệp.
        /// </summary>
        public static string File_could_not_be_found {
            get {
                return ResourceManager.GetString("File could not be found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp đã tồn tại.
        /// </summary>
        public static string File_is_already_exsists {
            get {
                return ResourceManager.GetString("File is already exsists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tệp.
        /// </summary>
        public static string File_not_found_ {
            get {
                return ResourceManager.GetString("File not found ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tập tin.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục đã tồn tại.
        /// </summary>
        public static string Folder_already_exists {
            get {
                return ResourceManager.GetString("Folder already exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thư mục.
        /// </summary>
        public static string Folder_could_not_be_found {
            get {
                return ResourceManager.GetString("Folder could not be found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thư mục.
        /// </summary>
        public static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Home_page {
            get {
                return ResourceManager.GetString("Home page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siêu dữ liệu không chính xác.
        /// </summary>
        public static string Incorrect_metadata {
            get {
                return ResourceManager.GetString("Incorrect metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID siêu dữ liệu không chính xác.
        /// </summary>
        public static string Incorrect_metadata_ID {
            get {
                return ResourceManager.GetString("Incorrect metadata ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không đúng.
        /// </summary>
        public static string Incorrect_password {
            get {
                return ResourceManager.GetString("Incorrect password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chế độ sáng.
        /// </summary>
        public static string Light_mode {
            get {
                return ResourceManager.GetString("Light mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất và đăng nhập lại.
        /// </summary>
        public static string Logout_and_login_again {
            get {
                return ResourceManager.GetString("Logout and login again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất khỏi tất cả các thiết bị.
        /// </summary>
        public static string Logout_from_all_devices {
            get {
                return ResourceManager.GetString("Logout from all devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất thành công.
        /// </summary>
        public static string Logout_successful {
            get {
                return ResourceManager.GetString("Logout successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp theo.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đợi một lát.
        /// </summary>
        public static string One_moment_please {
            get {
                return ResourceManager.GetString("One moment please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác khác.
        /// </summary>
        public static string Other_operations {
            get {
                return ResourceManager.GetString("Other operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không hợp lệ..
        /// </summary>
        public static string Passwords_do_not_match_ {
            get {
                return ResourceManager.GetString("Passwords do not match.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký tài khoản mới.
        /// </summary>
        public static string Register_a_new_account {
            get {
                return ResourceManager.GetString("Register a new account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký không thành công.
        /// </summary>
        public static string Registration_failed {
            get {
                return ResourceManager.GetString("Registration failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi tên.
        /// </summary>
        public static string ReName {
            get {
                return ResourceManager.GetString("ReName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Sign_In {
            get {
                return ResourceManager.GetString("Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập vào tài khoản của bạn.
        /// </summary>
        public static string Sign_in_to_your_account {
            get {
                return ResourceManager.GetString("Sign in to your account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string Sign_Out {
            get {
                return ResourceManager.GetString("Sign Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tùy chọn hệ thống.
        /// </summary>
        public static string System_preference {
            get {
                return ResourceManager.GetString("System preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng đã được xác thực.
        /// </summary>
        public static string The_user_has_been_authenticated {
            get {
                return ResourceManager.GetString("The user has been authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có gì ở đây để hiển thị.
        /// </summary>
        public static string There_is_nothing_to_show {
            get {
                return ResourceManager.GetString("There is nothing to show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài nguyên này yêu cầu X0 tuổi.
        /// </summary>
        public static string This_resource_requires_X0_years_old {
            get {
                return ResourceManager.GetString("This resource requires X0 years old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường này là bắt buộc.
        /// </summary>
        public static string ThisFieldIsRequired {
            get {
                return ResourceManager.GetString("ThisFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Để duy trì kết nối với chúng tôi vui lòng đăng nhập bằng thông tin cá nhân của bạn.
        /// </summary>
        public static string To_keep_connected_with_us_please_login_with_your_personal_info {
            get {
                return ResourceManager.GetString("To keep connected with us please login with your personal info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng đã được xác thực.
        /// </summary>
        public static string User_has_been_authenticated {
            get {
                return ResourceManager.GetString("User has been authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng đã tồn tại.
        /// </summary>
        public static string User_is_already_exists {
            get {
                return ResourceManager.GetString("User is already exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng được xác thực.
        /// </summary>
        public static string User_is_authenticated {
            get {
                return ResourceManager.GetString("User is authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng không tồn tại.
        /// </summary>
        public static string User_is_not_exists {
            get {
                return ResourceManager.GetString("User is not exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng không hợp lệ.
        /// </summary>
        public static string User_name_is_not_valid {
            get {
                return ResourceManager.GetString("User name is not valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không đúng.
        /// </summary>
        public static string User_or_password_is_incorrect {
            get {
                return ResourceManager.GetString("User or password is incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật người dùng không thành công.
        /// </summary>
        public static string User_update_failed {
            get {
                return ResourceManager.GetString("User update failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật người dùng thành công.
        /// </summary>
        public static string User_updated_successfully {
            get {
                return ResourceManager.GetString("User updated successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không đúng.
        /// </summary>
        public static string Username_or_password_incorrect {
            get {
                return ResourceManager.GetString("Username or password incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào mừng trở lại!.
        /// </summary>
        public static string Welcome_back_ {
            get {
                return ResourceManager.GetString("Welcome back!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã bị cấm đăng nhập, vui lòng thử lại lúc X0.
        /// </summary>
        public static string You_have_been_banned_from_logging_in__please_try_again_at_X0 {
            get {
                return ResourceManager.GetString("You have been banned from logging in, please try again at X0", resourceCulture);
            }
        }
    }
}
