//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessModels.Resources.AppLang", typeof(AppLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Độ chính xác.
        /// </summary>
        public static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hành động.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thiết bị mới.
        /// </summary>
        public static string Add_new_device {
            get {
                return ResourceManager.GetString("Add new device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thiết bị mới thành công.
        /// </summary>
        public static string Add_new_device_successfully {
            get {
                return ResourceManager.GetString("Add new device successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới bản ghi.
        /// </summary>
        public static string Add_new_record {
            get {
                return ResourceManager.GetString("Add new record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm cảm biến.
        /// </summary>
        public static string Add_sensor {
            get {
                return ResourceManager.GetString("Add_sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thẻ.
        /// </summary>
        public static string Add_tags {
            get {
                return ResourceManager.GetString("Add_tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại.
        /// </summary>
        public static string Already_existing {
            get {
                return ResourceManager.GetString("Already existing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi đã được phát hiện.
        /// </summary>
        public static string An_exception_has_been_found {
            get {
                return ResourceManager.GetString("An exception has been found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết đã tồn tại.
        /// </summary>
        public static string Article_already_exists {
            get {
                return ResourceManager.GetString("Article_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết không tồn tại.
        /// </summary>
        public static string Article_does_not_exist {
            get {
                return ResourceManager.GetString("Article_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tác giả.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR] {0}.
        /// </summary>
        public static string BaseHttpClientService_DeleteAsync__ERROR___0_ {
            get {
                return ResourceManager.GetString("BaseHttpClientService_DeleteAsync__ERROR___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR] {0}.
        /// </summary>
        public static string BaseHttpClientService_GetAsync__ERROR___0_ {
            get {
                return ResourceManager.GetString("BaseHttpClientService_GetAsync__ERROR___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR] {0}.
        /// </summary>
        public static string BaseHttpClientService_PostAsync__ERROR___0_ {
            get {
                return ResourceManager.GetString("BaseHttpClientService_PostAsync__ERROR___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR] {0}.
        /// </summary>
        public static string BaseHttpClientService_PutAsync__ERROR___0_ {
            get {
                return ResourceManager.GetString("BaseHttpClientService_PutAsync__ERROR___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Được xác minh.
        /// </summary>
        public static string Be_Verified {
            get {
                return ResourceManager.GetString("Be_Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh dấu.
        /// </summary>
        public static string Bookmark {
            get {
                return ResourceManager.GetString("Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt tập tin để tải lên.
        /// </summary>
        public static string Browse_File_to_upload {
            get {
                return ResourceManager.GetString("Browse File to upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian hiệu chuẩn.
        /// </summary>
        public static string Calibration_time {
            get {
                return ResourceManager.GetString("Calibration time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa thư mục hệ thống.
        /// </summary>
        public static string Cannot_delete_system_folder {
            get {
                return ResourceManager.GetString("Cannot delete system folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Nhiệt độ chip.
        /// </summary>
        public static string Chip_temperature {
            get {
                return ResourceManager.GetString("Chip temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân loại.
        /// </summary>
        public static string Classify {
            get {
                return ResourceManager.GetString("Classify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cộng đồng.
        /// </summary>
        public static string Community {
            get {
                return ResourceManager.GetString("Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã kết nối.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang kết nối.
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà sản xuất nội dung.
        /// </summary>
        public static string Content_creator {
            get {
                return ResourceManager.GetString("Content creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biên tập nội dung.
        /// </summary>
        public static string Content_editor {
            get {
                return ResourceManager.GetString("Content editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống quản lý nội dung.
        /// </summary>
        public static string Content_management_system {
            get {
                return ResourceManager.GetString("Content management system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã sao chép.
        /// </summary>
        public static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa thư mục gốc.
        /// </summary>
        public static string Could_not_delete_root_folder {
            get {
                return ResourceManager.GetString("Could not delete root folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy siêu dữ liệu.
        /// </summary>
        public static string Could_not_found_metadata {
            get {
                return ResourceManager.GetString("Could not found metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa thư mục gốc.
        /// </summary>
        public static string Could_not_remove_root_folder {
            get {
                return ResourceManager.GetString("Could not remove root folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài khoản.
        /// </summary>
        public static string Create_Account {
            get {
                return ResourceManager.GetString("Create Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo thất bại.
        /// </summary>
        public static string Create_failed {
            get {
                return ResourceManager.GetString("Create failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới.
        /// </summary>
        public static string Create_new {
            get {
                return ResourceManager.GetString("Create new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo thành công.
        /// </summary>
        public static string Create_successfully {
            get {
                return ResourceManager.GetString("Create successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thư mục hiện tại.
        /// </summary>
        public static string Current_folder_could_not_have_found {
            get {
                return ResourceManager.GetString("Current folder could not have found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa điểm hiện tại.
        /// </summary>
        public static string Current_location {
            get {
                return ResourceManager.GetString("Current location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chế độ tối.
        /// </summary>
        public static string Dark_mode {
            get {
                return ResourceManager.GetString("Dark mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa bỏ.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thiết bị.
        /// </summary>
        public static string Delete_device {
            get {
                return ResourceManager.GetString("Delete device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thiết bị thành công.
        /// </summary>
        public static string Delete_device_successfully {
            get {
                return ResourceManager.GetString("Delete device successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa vĩnh viễn.
        /// </summary>
        public static string Delete_forever {
            get {
                return ResourceManager.GetString("Delete forever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa lịch sử.
        /// </summary>
        public static string Delete_history {
            get {
                return ResourceManager.GetString("Delete history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa cảm biến.
        /// </summary>
        public static string Delete_sensor {
            get {
                return ResourceManager.GetString("Delete sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string Delete_successfully {
            get {
                return ResourceManager.GetString("Delete successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa cảm biến.
        /// </summary>
        public static string DeleteSensor {
            get {
                return ResourceManager.GetString("DeleteSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết bị.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm thiết bị.
        /// </summary>
        public static string Device_group {
            get {
                return ResourceManager.GetString("Device group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID thiết bị.
        /// </summary>
        public static string Device_ID {
            get {
                return ResourceManager.GetString("Device ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thiết bị.
        /// </summary>
        public static string Device_name {
            get {
                return ResourceManager.GetString("Device name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thiết bị.
        /// </summary>
        public static string Device_not_found {
            get {
                return ResourceManager.GetString("Device not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý nhóm thiết bị.
        /// </summary>
        public static string DeviceGroupManagement {
            get {
                return ResourceManager.GetString("DeviceGroupManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý thiết bị.
        /// </summary>
        public static string DeviceManagement {
            get {
                return ResourceManager.GetString("DeviceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã cắt kết nối.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không sử dụng mã thông báo này trên máy chủ cung cấp mã thông báo này.
        /// </summary>
        public static string Do_not_use_this_token_on_a_server_that_provides_this_token {
            get {
                return ResourceManager.GetString("Do not use this token on a server that provides this token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có thực sự muốn tải lại trang?.
        /// </summary>
        public static string Do_you_really_want_to_reload_the_page_ {
            get {
                return ResourceManager.GetString("Do you really want to reload the page?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải xuống.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình chỉnh sửa.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mật khẩu.
        /// </summary>
        public static string Enter_password {
            get {
                return ResourceManager.GetString("Enter password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngoại lệ.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tệp.
        /// </summary>
        public static string File_could_not_be_found {
            get {
                return ResourceManager.GetString("File could not be found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp đã tồn tại.
        /// </summary>
        public static string File_is_already_exsists {
            get {
                return ResourceManager.GetString("File is already exsists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tập tin mục chứa ký tự không hợp lệ: {0}.
        /// </summary>
        public static string File_name_contains_invalid_character__x {
            get {
                return ResourceManager.GetString("File name contains invalid character: x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tệp.
        /// </summary>
        public static string File_not_found_ {
            get {
                return ResourceManager.GetString("File not found ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải tập tin lên.
        /// </summary>
        public static string File_upload {
            get {
                return ResourceManager.GetString("File upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tập tin.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version phần mềm thiết bị.
        /// </summary>
        public static string Firmware_version {
            get {
                return ResourceManager.GetString("Firmware version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục đã tồn tại.
        /// </summary>
        public static string Folder_already_exists {
            get {
                return ResourceManager.GetString("Folder already exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thư mục.
        /// </summary>
        public static string Folder_could_not_be_found {
            get {
                return ResourceManager.GetString("Folder could not be found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Di chuyển thư mục thành công.
        /// </summary>
        public static string Folder_moved_successfully {
            get {
                return ResourceManager.GetString("Folder moved successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thư mục chứa ký tự không hợp lệ: {0}.
        /// </summary>
        public static string Folder_name_contains_invalid_character__x {
            get {
                return ResourceManager.GetString("Folder name contains invalid character: x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thư mục.
        /// </summary>
        public static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhận liên kết.
        /// </summary>
        public static string Get_link {
            get {
                return ResourceManager.GetString("Get link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Home_page {
            get {
                return ResourceManager.GetString("Home page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siêu dữ liệu không chính xác.
        /// </summary>
        public static string Incorrect_metadata {
            get {
                return ResourceManager.GetString("Incorrect metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID siêu dữ liệu không chính xác.
        /// </summary>
        public static string Incorrect_metadata_ID {
            get {
                return ResourceManager.GetString("Incorrect metadata ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác không đúng.
        /// </summary>
        public static string Incorrect_operation {
            get {
                return ResourceManager.GetString("Incorrect operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không đúng.
        /// </summary>
        public static string Incorrect_password {
            get {
                return ResourceManager.GetString("Incorrect password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khóa không hợp lệ.
        /// </summary>
        public static string Invalid_key {
            get {
                return ResourceManager.GetString("Invalid_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ IP.
        /// </summary>
        public static string IP_address {
            get {
                return ResourceManager.GetString("IP address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ IP đã được sử dụng.
        /// </summary>
        public static string IP_address_already_used {
            get {
                return ResourceManager.GetString("IP_address_already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ IP không hợp lệ.
        /// </summary>
        public static string IP_address_is_not_valid {
            get {
                return ResourceManager.GetString("IP address is not valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tham gia các Nhà thiết kế giàu kinh nghiệm trên nền tảng này.
        /// </summary>
        public static string Join_experienced_Designers {
            get {
                return ResourceManager.GetString("Join_experienced_Designers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngôn ngữ.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chế độ sáng.
        /// </summary>
        public static string Light_mode {
            get {
                return ResourceManager.GetString("Light mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường dẫn.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tải.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa điểm.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất và đăng nhập lại.
        /// </summary>
        public static string Logout_and_login_again {
            get {
                return ResourceManager.GetString("Logout and login again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất khỏi tất cả các thiết bị.
        /// </summary>
        public static string Logout_from_all_devices {
            get {
                return ResourceManager.GetString("Logout from all devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất thành công.
        /// </summary>
        public static string Logout_successful {
            get {
                return ResourceManager.GetString("Logout successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ MAC.
        /// </summary>
        public static string MAC_address {
            get {
                return ResourceManager.GetString("MAC address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chi MAC đã được sử dụng.
        /// </summary>
        public static string MAC_address_already_used {
            get {
                return ResourceManager.GetString("MAC address already used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ MAC không hợp lệ.
        /// </summary>
        public static string MAC_address_is_not_valid {
            get {
                return ResourceManager.GetString("MAC address is not valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà sản xuất.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phút.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian chỉnh sửa.
        /// </summary>
        public static string Modified_time {
            get {
                return ResourceManager.GetString("Modified time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Di chuyển {0}.
        /// </summary>
        public static string Move__0_ {
            get {
                return ResourceManager.GetString("Move _0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Di chuyển đến.
        /// </summary>
        public static string Move_to {
            get {
                return ResourceManager.GetString("Move to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Di chuyển vào thùng rác.
        /// </summary>
        public static string Move_to_recycle_bin {
            get {
                return ResourceManager.GetString("Move to recycle bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive của tôi.
        /// </summary>
        public static string My_Drive {
            get {
                return ResourceManager.GetString("My Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mới.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mực mới.
        /// </summary>
        public static string New_folder {
            get {
                return ResourceManager.GetString("New folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp theo.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đợi một lát.
        /// </summary>
        public static string One_moment_please {
            get {
                return ResourceManager.GetString("One moment please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiết bị trực tuyến.
        /// </summary>
        public static string Online_devices {
            get {
                return ResourceManager.GetString("Online devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác khác.
        /// </summary>
        public static string Other_operations {
            get {
                return ResourceManager.GetString("Other operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientX: {0} 
        ///ClientY: {1}.
        /// </summary>
        public static string Page_ContextMenuClick_ {
            get {
                return ResourceManager.GetString("Page_ContextMenuClick_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số trang.
        /// </summary>
        public static string Page_number {
            get {
                return ResourceManager.GetString("Page number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước trang.
        /// </summary>
        public static string Page_size {
            get {
                return ResourceManager.GetString("Page size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không hợp lệ..
        /// </summary>
        public static string Passwords_do_not_match_ {
            get {
                return ResourceManager.GetString("Passwords do not match.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái xử lý.
        /// </summary>
        public static string Process_status {
            get {
                return ResourceManager.GetString("Process status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR] {0}.
        /// </summary>
        public static string ProtectedSessionStorage_GetAsync__ERROR___0_ {
            get {
                return ResourceManager.GetString("ProtectedSessionStorage_GetAsync__ERROR___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position is out of range..
        /// </summary>
        public static string Raid5Stream_Position_Position_is_out_of_range_ {
            get {
                return ResourceManager.GetString("Raid5Stream_Position_Position_is_out_of_range_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang kết nối lại.
        /// </summary>
        public static string Reconnecting {
            get {
                return ResourceManager.GetString("Reconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thùng rác.
        /// </summary>
        public static string Recycle_bin {
            get {
                return ResourceManager.GetString("Recycle bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm mới dữ liệu.
        /// </summary>
        public static string Refresh_data {
            get {
                return ResourceManager.GetString("Refresh data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký tài khoản mới.
        /// </summary>
        public static string Register_a_new_account {
            get {
                return ResourceManager.GetString("Register a new account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký không thành công.
        /// </summary>
        public static string Registration_failed {
            get {
                return ResourceManager.GetString("Registration failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải lại.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có thực sự muốn tải lại trang không?.
        /// </summary>
        public static string Reload_page_confirmation {
            get {
                return ResourceManager.GetString("Reload_page_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi tên.
        /// </summary>
        public static string ReName {
            get {
                return ResourceManager.GetString("ReName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi tên thiết bị.
        /// </summary>
        public static string Rename_device {
            get {
                return ResourceManager.GetString("Rename_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi tên tệp.
        /// </summary>
        public static string Rename_file {
            get {
                return ResourceManager.GetString("Rename_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi tên thư mục.
        /// </summary>
        public static string Rename_folder {
            get {
                return ResourceManager.GetString("Rename_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi tên cảm biến.
        /// </summary>
        public static string Rename_sensor {
            get {
                return ResourceManager.GetString("Rename_sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã yêu cầu.
        /// </summary>
        public static string Requested {
            get {
                return ResourceManager.GetString("Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu.
        /// </summary>
        public static string Requesting {
            get {
                return ResourceManager.GetString("Requesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường bắt buộc.
        /// </summary>
        public static string Required_field {
            get {
                return ResourceManager.GetString("Required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục gốc không được tìm thấy.
        /// </summary>
        public static string Root_folder_could_not_be_found {
            get {
                return ResourceManager.GetString("Root folder could not be found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngoại tuyến.
        /// </summary>
        public static string Routes_Offline_Offline {
            get {
                return ResourceManager.GetString("Routes_Offline_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trực tuyến.
        /// </summary>
        public static string Routes_Online_Online {
            get {
                return ResourceManager.GetString("Routes_Online_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang đã bị ẩn.
        /// </summary>
        public static string Routes_PageHide_The_page_has_been_hidden {
            get {
                return ResourceManager.GetString("Routes_PageHide_The_page_has_been_hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang đã được hiển thị.
        /// </summary>
        public static string Routes_PageShow_The_page_has_been_displayed {
            get {
                return ResourceManager.GetString("Routes_PageShow_The_page_has_been_displayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dòng/trang.
        /// </summary>
        public static string Rows_per_page {
            get {
                return ResourceManager.GetString("Rows per page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm thiết bị.
        /// </summary>
        public static string Search_device {
            get {
                return ResourceManager.GetString("Search device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tìm kiếm.
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giây.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn thiết bị.
        /// </summary>
        public static string Select_device {
            get {
                return ResourceManager.GetString("Select device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn cảm biến.
        /// </summary>
        public static string Select_sensor {
            get {
                return ResourceManager.GetString("Select sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn thời gian.
        /// </summary>
        public static string Select_time {
            get {
                return ResourceManager.GetString("Select time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm biến.
        /// </summary>
        public static string Sensor {
            get {
                return ResourceManager.GetString("Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID cảm biến.
        /// </summary>
        public static string Sensor_ID {
            get {
                return ResourceManager.GetString("Sensor ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm biến không tìm thấy.
        /// </summary>
        public static string Sensor_not_found {
            get {
                return ResourceManager.GetString("Sensor not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm biến.
        /// </summary>
        public static string Sensors {
            get {
                return ResourceManager.GetString("Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chia sẻ.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh bên.
        /// </summary>
        public static string Sidebar {
            get {
                return ResourceManager.GetString("Sidebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Sign_In {
            get {
                return ResourceManager.GetString("Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập vào tài khoản của bạn.
        /// </summary>
        public static string Sign_in_to_your_account {
            get {
                return ResourceManager.GetString("Sign in to your account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string Sign_Out {
            get {
                return ResourceManager.GetString("Sign Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ mạnh tín hiệu.
        /// </summary>
        public static string Signal_strength {
            get {
                return ResourceManager.GetString("Signal strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải lên thành công.
        /// </summary>
        public static string Successfully_uploaded {
            get {
                return ResourceManager.GetString("Successfully uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tùy chọn hệ thống.
        /// </summary>
        public static string System_preference {
            get {
                return ResourceManager.GetString("System preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {first_item}-{last_item} / {all_items}.
        /// </summary>
        public static string Table_row_content_format_page_per_row {
            get {
                return ResourceManager.GetString("Table_row_content_format_page_per_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm soát nội dung và chức năng của ứng dụng của bạn bằng CMS không đầu.
        /// </summary>
        public static string Take_control_of_your_application_s_content_and_functionality_with_a_Headless_CMS {
            get {
                return ResourceManager.GetString("Take control of your application\'s content and functionality with a Headless CMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư mục đích không được tìm thấy.
        /// </summary>
        public static string Target_folder_could_not_have_found {
            get {
                return ResourceManager.GetString("Target folder could not have found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document already exists.
        /// </summary>
        public static string The_document_already_exists {
            get {
                return ResourceManager.GetString("The document already exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang bạn đang tìm kiếm không tồn tại. Đừng lo lắng, điều đó sẽ xảy ra với những người tốt nhất trong chúng ta!.
        /// </summary>
        public static string The_page_you_were_looking_for_does_not_exist__Don_t_worry__it_happens_to_the_best_of_us_ {
            get {
                return ResourceManager.GetString("The page you were looking for does not exist. Don\'t worry, it happens to the best" +
                        " of us!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài nguyên bạn đang tìm không tồn tại.
        /// </summary>
        public static string The_resource_you_are_looking_for_does_not_exist {
            get {
                return ResourceManager.GetString("The resource you are looking for does not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng đã được xác thực.
        /// </summary>
        public static string The_user_has_been_authenticated {
            get {
                return ResourceManager.GetString("The user has been authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có gì ở đây để hiển thị.
        /// </summary>
        public static string There_is_nothing_to_show {
            get {
                return ResourceManager.GetString("There is nothing to show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đây là trường bắt buộc.
        /// </summary>
        public static string This_field_is_required {
            get {
                return ResourceManager.GetString("This field is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài nguyên này được bảo vệ bởi mật khẩu.
        /// </summary>
        public static string This_resource_is_protected_by_password {
            get {
                return ResourceManager.GetString("This resource is protected by password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài nguyên này yêu cầu {0} tuổi.
        /// </summary>
        public static string This_resource_requires_X0_years_old {
            get {
                return ResourceManager.GetString("This resource requires X0 years old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường này là bắt buộc.
        /// </summary>
        public static string ThisFieldIsRequired {
            get {
                return ResourceManager.GetString("ThisFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian stamp.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Để duy trì kết nối với chúng tôi vui lòng đăng nhập bằng thông tin cá nhân của bạn.
        /// </summary>
        public static string To_keep_connected_with_us_please_login_with_your_personal_info {
            get {
                return ResourceManager.GetString("To keep connected with us please login with your personal info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số bản ghi.
        /// </summary>
        public static string Total_records {
            get {
                return ResourceManager.GetString("Total_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị đo.
        /// </summary>
        public static string Unit_of_measurement {
            get {
                return ResourceManager.GetString("Unit of measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thiết bị.
        /// </summary>
        public static string Update_device {
            get {
                return ResourceManager.GetString("Update device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thất bại.
        /// </summary>
        public static string Update_failed {
            get {
                return ResourceManager.GetString("Update_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật cảm biến.
        /// </summary>
        public static string Update_sensor {
            get {
                return ResourceManager.GetString("Update sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng đã được xác thực.
        /// </summary>
        public static string User_has_been_authenticated {
            get {
                return ResourceManager.GetString("User has been authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin người dùng là bắt buộc.
        /// </summary>
        public static string User_information_is_required {
            get {
                return ResourceManager.GetString("User information is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng đã tồn tại.
        /// </summary>
        public static string User_is_already_exists {
            get {
                return ResourceManager.GetString("User is already exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng được xác thực.
        /// </summary>
        public static string User_is_authenticated {
            get {
                return ResourceManager.GetString("User is authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng không tồn tại.
        /// </summary>
        public static string User_is_not_exists {
            get {
                return ResourceManager.GetString("User is not exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng không hợp lệ.
        /// </summary>
        public static string User_name_is_not_valid {
            get {
                return ResourceManager.GetString("User name is not valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không đúng.
        /// </summary>
        public static string User_or_password_is_incorrect {
            get {
                return ResourceManager.GetString("User or password is incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật người dùng không thành công.
        /// </summary>
        public static string User_update_failed {
            get {
                return ResourceManager.GetString("User update failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật người dùng thành công.
        /// </summary>
        public static string User_updated_successfully {
            get {
                return ResourceManager.GetString("User updated successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không đúng.
        /// </summary>
        public static string Username_or_password_incorrect {
            get {
                return ResourceManager.GetString("Username or password incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào mừng trở lại!.
        /// </summary>
        public static string Welcome_back_ {
            get {
                return ResourceManager.GetString("Welcome back!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã bị cấm đăng nhập, vui lòng thử lại lúc {0}.
        /// </summary>
        public static string You_have_been_banned_from_logging_in__please_try_again_at_X0 {
            get {
                return ResourceManager.GetString("You have been banned from logging in, please try again at X0", resourceCulture);
            }
        }
    }
}
