//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModels.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppLang_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLang_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessModels.Resources.AppLang.en-US", typeof(AppLang_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One moment please.
        /// </summary>
        public static string One_moment_please {
            get {
                return ResourceManager.GetString("One moment please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has been authenticated.
        /// </summary>
        public static string The_user_has_been_authenticated {
            get {
                return ResourceManager.GetString("The user has been authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to show.
        /// </summary>
        public static string There_is_nothing_to_show {
            get {
                return ResourceManager.GetString("There is nothing to show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This resource requires {0} years old.
        /// </summary>
        public static string This_resource_requires__0__years_old {
            get {
                return ResourceManager.GetString("This resource requires {0} years old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been authenticated.
        /// </summary>
        public static string User_has_been_authenticated {
            get {
                return ResourceManager.GetString("User has been authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already exists.
        /// </summary>
        public static string User_is_already_exists {
            get {
                return ResourceManager.GetString("User is already exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is authenticated.
        /// </summary>
        public static string User_is_authenticated {
            get {
                return ResourceManager.GetString("User is authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not exists.
        /// </summary>
        public static string User_is_not_exists {
            get {
                return ResourceManager.GetString("User is not exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is not valid.
        /// </summary>
        public static string User_name_is_not_valid {
            get {
                return ResourceManager.GetString("User name is not valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or password is incorrect.
        /// </summary>
        public static string User_or_password_is_incorrect {
            get {
                return ResourceManager.GetString("User or password is incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User update failed.
        /// </summary>
        public static string User_update_failed {
            get {
                return ResourceManager.GetString("User update failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated successfully.
        /// </summary>
        public static string User_updated_successfully {
            get {
                return ResourceManager.GetString("User updated successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password incorrect.
        /// </summary>
        public static string Username_or_password_incorrect {
            get {
                return ResourceManager.GetString("Username or password incorrect", resourceCulture);
            }
        }
    }
}
